import {
  Controller, Get, Post, Put, Delete,
  Body, Param, Query, Request, Res,
  UseGuards, UseInterceptors, UploadedFile,
  ParseFilePipe, MaxFileSizeValidator, FileTypeValidator,
} from '@nestjs/common';
import { FileInterceptor } from '@nestjs/platform-express';
import { ApiTags, ApiBearerAuth, ApiOperation, ApiConsumes, ApiBody } from '@nestjs/swagger';
import { AuthGuard } from '@nestjs/passport';
import type { Response } from 'express';
import { DokumenService } from './dokumen.service.js';
import { Roles, RolesGuard } from '../auth/roles.guard.js';

@ApiTags('Dokumen')
@ApiBearerAuth()
@UseGuards(AuthGuard('jwt'), RolesGuard)
@Controller('dokumen')
export class DokumenController {
  constructor(private dokumenService: DokumenService) {}

  // ─── Generate ─────────────────────────────────────────────────────────────────

  @Post('kartu-anggota/:anggotaId/generate')
  @Roles('superadmin', 'admin_distrik')
  @ApiOperation({ summary: 'Generate kartu anggota PDF for a member' })
  generateKartu(@Param('anggotaId') anggotaId: string, @Request() req: any) {
    return this.dokumenService.generateKartuAnggota(+anggotaId, req.user.id);
  }

  @Post('sertifikat/:calonAnggotaId/:kegiatanId/generate')
  @Roles('superadmin', 'admin_distrik', 'admin_kegiatan')
  @ApiOperation({ summary: 'Generate sertifikat pendadaran PDF from hasil pendadaran' })
  generateSertifikat(
    @Param('calonAnggotaId') calonAnggotaId: string,
    @Param('kegiatanId') kegiatanId: string,
    @Request() req: any,
  ) {
    return this.dokumenService.generateSertifikat(+calonAnggotaId, +kegiatanId, req.user.id);
  }

  @Post('piagam/:anggotaId/generate')
  @Roles('superadmin', 'admin_distrik')
  @ApiOperation({ summary: 'Generate piagam prestasi PDF' })
  generatePiagam(
    @Param('anggotaId') anggotaId: string,
    @Body('prestasi') prestasi: string,
    @Request() req: any,
  ) {
    return this.dokumenService.generatePiagam(+anggotaId, prestasi, req.user.id);
  }

  // ─── Verify & Download ────────────────────────────────────────────────────────

  @Get('verify/:token')
  @ApiOperation({ summary: 'Public verification of document via QR token' })
  async verify(@Param('token') token: string) {
    return this.dokumenService.verifyDocument(token);
  }

  @Get('download/:anggotaId/:type')
  @ApiOperation({ summary: 'Download document by type code (KARTU_ANGGOTA, SERTIFIKAT_PENDADARAN, PIAGAM_PRESTASI)' })
  async download(
    @Param('anggotaId') anggotaId: string,
    @Param('type') type: string,
    @Res() res: Response,
  ) {
    const url = await this.dokumenService.getDocumentUrl(+anggotaId, type);
    return res.redirect(url);
  }

  @Post(':id/revoke')
  @Roles('superadmin')
  @ApiOperation({ summary: 'Revoke an issued document' })
  revoke(@Param('id') id: string) {
    return this.dokumenService.revokeDocument(+id);
  }

  // ─── Document Types ───────────────────────────────────────────────────────────

  @Post('types')
  @Roles('superadmin')
  @ApiOperation({ summary: 'Create a new document type' })
  createType(
    @Body() data: {
      code: string;
      name: string;
      category: string;
      isAutoGenerated?: boolean;
      requiresApproval?: boolean;
    },
  ) {
    return this.dokumenService.createDocumentType(data);
  }

  @Get('types')
  @ApiOperation({ summary: 'Get all document types with template & issued document counts' })
  findAllTypes() {
    return this.dokumenService.findAllDocumentTypes();
  }

  @Get('types/:id')
  @ApiOperation({ summary: 'Get document type by ID with active templates, signers, stamps' })
  findTypeById(@Param('id') id: string) {
    return this.dokumenService.findDocumentTypeById(+id);
  }

  @Put('types/:id')
  @Roles('superadmin')
  @ApiOperation({ summary: 'Update document type' })
  updateType(
    @Param('id') id: string,
    @Body() data: Partial<{
      name: string;
      category: string;
      isAutoGenerated: boolean;
      requiresApproval: boolean;
      isActive: boolean;
    }>,
  ) {
    return this.dokumenService.updateDocumentType(+id, data);
  }

  @Delete('types/:id')
  @Roles('superadmin')
  @ApiOperation({ summary: 'Soft-delete document type (set isActive = false)' })
  deleteType(@Param('id') id: string) {
    return this.dokumenService.deleteDocumentType(+id);
  }

  // ─── Document Templates ───────────────────────────────────────────────────────

  @Post('templates')
  @Roles('superadmin', 'admin_distrik')
  @ApiOperation({ summary: 'Upload a new document template file' })
  @ApiConsumes('multipart/form-data')
  @ApiBody({
    schema: {
      type: 'object',
      required: ['file', 'documentTypeId', 'name'],
      properties: {
        file: { type: 'string', format: 'binary', description: 'Template file (HTML/PDF/image)' },
        documentTypeId: { type: 'number' },
        name: { type: 'string' },
        layoutJson: { type: 'string', description: 'JSON string of layout config' },
        scopeType: { type: 'string', enum: ['nasional', 'distrik', 'wilayah', 'ranting'] },
        scopeId: { type: 'number' },
      },
    },
  })
  @UseInterceptors(FileInterceptor('file', { limits: { fileSize: 20 * 1024 * 1024 } }))
  createTemplate(
    @Request() req: any,
    @UploadedFile(
      new ParseFilePipe({
        validators: [new MaxFileSizeValidator({ maxSize: 20 * 1024 * 1024 })],
      }),
    )
    file: Express.Multer.File,
    @Body('documentTypeId') documentTypeId: string,
    @Body('name') name: string,
    @Body('layoutJson') layoutJson?: string,
    @Body('scopeType') scopeType?: string,
    @Body('scopeId') scopeId?: string,
  ) {
    return this.dokumenService.createDocumentTemplate(
      file,
      {
        documentTypeId: +documentTypeId,
        name,
        layoutJson: layoutJson ? JSON.parse(layoutJson) : undefined,
        scopeType,
        scopeId: scopeId ? +scopeId : undefined,
      },
      req.user.id,
    );
  }

  @Get('templates')
  @ApiOperation({ summary: 'Get all document templates. Filter: ?documentTypeId=1' })
  findAllTemplates(@Query('documentTypeId') documentTypeId?: string) {
    return this.dokumenService.findAllDocumentTemplates(documentTypeId ? +documentTypeId : undefined);
  }

  @Get('templates/:id')
  @ApiOperation({ summary: 'Get document template by ID (includes signed file URL)' })
  findTemplateById(@Param('id') id: string) {
    return this.dokumenService.findDocumentTemplateById(+id);
  }

  @Put('templates/:id')
  @Roles('superadmin', 'admin_distrik')
  @ApiOperation({ summary: 'Update document template metadata (name, layoutJson, isActive, scope)' })
  updateTemplate(
    @Param('id') id: string,
    @Body() data: Partial<{
      name: string;
      layoutJson: Record<string, unknown>;
      isActive: boolean;
      scopeType: string;
      scopeId: number;
    }>,
  ) {
    return this.dokumenService.updateDocumentTemplate(+id, data);
  }

  @Delete('templates/:id')
  @Roles('superadmin')
  @ApiOperation({ summary: 'Delete document template and its file from storage' })
  deleteTemplate(@Param('id') id: string) {
    return this.dokumenService.deleteDocumentTemplate(+id);
  }

  // ─── Document Signers ─────────────────────────────────────────────────────────

  @Post('signers')
  @Roles('superadmin', 'admin_distrik')
  @ApiOperation({ summary: 'Upload a signer with signature image' })
  @ApiConsumes('multipart/form-data')
  @ApiBody({
    schema: {
      type: 'object',
      required: ['file', 'name', 'position'],
      properties: {
        file: { type: 'string', format: 'binary', description: 'Signature image (PNG/JPEG, maks 5 MB)' },
        name: { type: 'string' },
        position: { type: 'string' },
        documentTypeId: { type: 'number' },
        scopeType: { type: 'string' },
        scopeId: { type: 'number' },
      },
    },
  })
  @UseInterceptors(FileInterceptor('file', { limits: { fileSize: 5 * 1024 * 1024 } }))
  createSigner(
    @UploadedFile(
      new ParseFilePipe({
        validators: [
          new MaxFileSizeValidator({ maxSize: 5 * 1024 * 1024 }),
          new FileTypeValidator({ fileType: /^image\/(jpeg|png|webp)$/ }),
        ],
      }),
    )
    file: Express.Multer.File,
    @Body('name') name: string,
    @Body('position') position: string,
    @Body('documentTypeId') documentTypeId?: string,
    @Body('scopeType') scopeType?: string,
    @Body('scopeId') scopeId?: string,
  ) {
    return this.dokumenService.createDocumentSigner(file, {
      name,
      position,
      documentTypeId: documentTypeId ? +documentTypeId : undefined,
      scopeType,
      scopeId: scopeId ? +scopeId : undefined,
    });
  }

  @Get('signers')
  @ApiOperation({ summary: 'Get all active signers with signed URLs. Filter: ?documentTypeId=1' })
  findAllSigners(@Query('documentTypeId') documentTypeId?: string) {
    return this.dokumenService.findAllDocumentSigners(documentTypeId ? +documentTypeId : undefined);
  }

  @Put('signers/:id')
  @Roles('superadmin', 'admin_distrik')
  @ApiOperation({ summary: 'Update signer name, position, or active status' })
  updateSigner(
    @Param('id') id: string,
    @Body() data: Partial<{ name: string; position: string; isActive: boolean }>,
  ) {
    return this.dokumenService.updateDocumentSigner(+id, data);
  }

  @Delete('signers/:id')
  @Roles('superadmin')
  @ApiOperation({ summary: 'Delete signer and remove signature file from storage' })
  deleteSigner(@Param('id') id: string) {
    return this.dokumenService.deleteDocumentSigner(+id);
  }

  // ─── Document Stamps ──────────────────────────────────────────────────────────

  @Post('stamps')
  @Roles('superadmin', 'admin_distrik')
  @ApiOperation({ summary: 'Upload an organization stamp image' })
  @ApiConsumes('multipart/form-data')
  @ApiBody({
    schema: {
      type: 'object',
      required: ['file', 'name'],
      properties: {
        file: { type: 'string', format: 'binary', description: 'Stamp image (PNG/JPEG, maks 5 MB)' },
        name: { type: 'string' },
        documentTypeId: { type: 'number' },
        scopeType: { type: 'string' },
        scopeId: { type: 'number' },
      },
    },
  })
  @UseInterceptors(FileInterceptor('file', { limits: { fileSize: 5 * 1024 * 1024 } }))
  createStamp(
    @UploadedFile(
      new ParseFilePipe({
        validators: [
          new MaxFileSizeValidator({ maxSize: 5 * 1024 * 1024 }),
          new FileTypeValidator({ fileType: /^image\/(jpeg|png|webp)$/ }),
        ],
      }),
    )
    file: Express.Multer.File,
    @Body('name') name: string,
    @Body('documentTypeId') documentTypeId?: string,
    @Body('scopeType') scopeType?: string,
    @Body('scopeId') scopeId?: string,
  ) {
    return this.dokumenService.createDocumentStamp(file, {
      name,
      documentTypeId: documentTypeId ? +documentTypeId : undefined,
      scopeType,
      scopeId: scopeId ? +scopeId : undefined,
    });
  }

  @Get('stamps')
  @ApiOperation({ summary: 'Get all active stamps with signed URLs. Filter: ?documentTypeId=1' })
  findAllStamps(@Query('documentTypeId') documentTypeId?: string) {
    return this.dokumenService.findAllDocumentStamps(documentTypeId ? +documentTypeId : undefined);
  }

  @Put('stamps/:id')
  @Roles('superadmin', 'admin_distrik')
  @ApiOperation({ summary: 'Update stamp name or active status' })
  updateStamp(
    @Param('id') id: string,
    @Body() data: Partial<{ name: string; isActive: boolean }>,
  ) {
    return this.dokumenService.updateDocumentStamp(+id, data);
  }

  @Delete('stamps/:id')
  @Roles('superadmin')
  @ApiOperation({ summary: 'Delete stamp and remove image from storage' })
  deleteStamp(@Param('id') id: string) {
    return this.dokumenService.deleteDocumentStamp(+id);
  }
}
