import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Seeding database...');

  // ═══════════════════════════════════════════
  // ROLES
  // ═══════════════════════════════════════════
  const roles = await Promise.all([
    prisma.role.upsert({
      where: { id: 1 }, update: {},
      create: { id: 1, nama: 'Superadmin', scope: 'superadmin', permissions: ['*'] },
    }),
    prisma.role.upsert({
      where: { id: 2 }, update: {},
      create: { id: 2, nama: 'Admin Distrik', scope: 'admin_distrik', permissions: ['anggota:*', 'iuran:*', 'konten:approve', 'dokumen:*', 'claim:*'] },
    }),
    prisma.role.upsert({
      where: { id: 3 }, update: {},
      create: { id: 3, nama: 'Admin Wilayah', scope: 'admin_wilayah', permissions: ['anggota:read', 'anggota:write', 'latihan:read'] },
    }),
    prisma.role.upsert({
      where: { id: 4 }, update: {},
      create: { id: 4, nama: 'Admin Ranting', scope: 'admin_ranting', permissions: ['anggota:read', 'latihan:*', 'absensi:*'] },
    }),
    prisma.role.upsert({
      where: { id: 5 }, update: {},
      create: { id: 5, nama: 'Pelatih', scope: 'pelatih', permissions: ['latihan:*', 'absensi:*'] },
    }),
    prisma.role.upsert({
      where: { id: 6 }, update: {},
      create: { id: 6, nama: 'Penguji', scope: 'penguji', permissions: ['pendadaran:*'] },
    }),
    prisma.role.upsert({
      where: { id: 7 }, update: {},
      create: { id: 7, nama: 'Anggota', scope: 'anggota', permissions: ['self:*', 'anggota:read'] },
    }),
  ]);
  console.log(`✓ Created ${roles.length} roles`);

  // ═══════════════════════════════════════════
  // ORGANISASI HIERARCHY
  // ═══════════════════════════════════════════
  const nasional = await prisma.nasional.upsert({
    where: { id: 1 }, update: {},
    create: { id: 1, nama: 'THS-THM Nasional', kode: 'THS-NAS' },
  });

  const distrik = await prisma.distrik.upsert({
    where: { id: 1 }, update: {},
    create: { id: 1, nama: 'Distrik Larantuka', kodeDistrik: 'DIST-LRT', nasionalId: nasional.id, alamat: 'Larantuka, Flores Timur, NTT' },
  });

  const wilayah = await prisma.wilayah.upsert({
    where: { id: 1 }, update: {},
    create: { id: 1, nama: 'Wilayah Larantuka 1', kodeWilayah: 'WIL-LRT1', distrikId: distrik.id },
  });

  const ranting = await prisma.ranting.upsert({
    where: { id: 1 }, update: {},
    create: { id: 1, nama: 'Ranting St. Yosef', kodeRanting: 'RAN-YOSEF', wilayahId: wilayah.id, lokasiLatihan: 'Aula Gereja Katedral Larantuka' },
  });
  console.log('✓ Created organization hierarchy (Nasional → Distrik → Wilayah → Ranting)');

  // ═══════════════════════════════════════════
  // DOCUMENT TYPES
  // ═══════════════════════════════════════════
  const docTypes = await Promise.all([
    prisma.documentType.upsert({
      where: { code: 'KARTU_ANGGOTA' }, update: {},
      create: { code: 'KARTU_ANGGOTA', name: 'Kartu Anggota', category: 'kartu', isAutoGenerated: true },
    }),
    prisma.documentType.upsert({
      where: { code: 'SERTIFIKAT_PENDADARAN' }, update: {},
      create: { code: 'SERTIFIKAT_PENDADARAN', name: 'Sertifikat Pendadaran', category: 'sertifikat', isAutoGenerated: true },
    }),
    prisma.documentType.upsert({
      where: { code: 'PIAGAM_PRESTASI' }, update: {},
      create: { code: 'PIAGAM_PRESTASI', name: 'Piagam Prestasi', category: 'piagam', isAutoGenerated: true },
    }),
  ]);
  console.log(`✓ Created ${docTypes.length} document types`);

  // ═══════════════════════════════════════════
  // USERS
  // ═══════════════════════════════════════════
  const adminPassword = await bcrypt.hash('admin123', 10);
  const admin = await prisma.user.upsert({
    where: { email: 'admin@ths-thm.org' },
    update: {},
    create: {
      name: 'Admin Super',
      email: 'admin@ths-thm.org',
      nomorHp: '081234567890',
      passwordHash: adminPassword,
      roleId: 1,
      scopeType: 'nasional',
      scopeId: nasional.id,
      isActive: true,
    },
  });

  const pelatihPassword = await bcrypt.hash('pelatih123', 10);
  const pelatihUser = await prisma.user.upsert({
    where: { email: 'pelatih@ths-thm.org' },
    update: {},
    create: {
      name: 'Pelatih Satu',
      email: 'pelatih@ths-thm.org',
      nomorHp: '081234567891',
      passwordHash: pelatihPassword,
      roleId: 5,
      scopeType: 'ranting',
      scopeId: ranting.id,
      isActive: true,
    },
  });
  console.log('✓ Created admin & pelatih users');

  // ═══════════════════════════════════════════
  // ANGGOTA + USER ACCOUNTS
  // ═══════════════════════════════════════════
  const anggotaData = [
    { nomorAnggota: 'THS-001', namaLengkap: 'Yohanes Don Bosco', jenisKelamin: 'L', tempatLahir: 'Larantuka', tanggalLahir: new Date('1995-03-15'), alamat: 'Jl. Gereja No. 1, Larantuka', noHp: '081234567801', email: 'yohanes@example.com', noHpUser: '081234567801' },
    { nomorAnggota: 'THS-002', namaLengkap: 'Maria Goreti', jenisKelamin: 'P', tempatLahir: 'Maumere', tanggalLahir: new Date('1998-07-22'), alamat: 'Jl. Katedral No. 5, Maumere', noHp: '081234567802', email: 'maria@example.com', noHpUser: '081234567802' },
    { nomorAnggota: 'THS-003', namaLengkap: 'Petrus Paulus', jenisKelamin: 'L', tempatLahir: 'Ende', tanggalLahir: new Date('1993-11-08'), alamat: 'Jl. Merdeka No. 12, Ende', noHp: '081234567803', email: 'petrus@example.com', noHpUser: '081234567803' },
    { nomorAnggota: 'THS-004', namaLengkap: 'Agnes Theresia', jenisKelamin: 'P', tempatLahir: 'Lewoleba', tanggalLahir: new Date('2000-01-30'), alamat: 'Jl. Pasar No. 3, Lewoleba', noHp: '081234567804', email: 'agnes@example.com', noHpUser: '081234567804' },
    { nomorAnggota: 'THS-005', namaLengkap: 'Fransiskus Asisi', jenisKelamin: 'L', tempatLahir: 'Larantuka', tanggalLahir: new Date('1996-05-20'), alamat: 'Jl. Pantai No. 8, Larantuka', noHp: '081234567805', email: 'frans@example.com', noHpUser: '081234567805' },
  ];

  const anggotaPassword = await bcrypt.hash('anggota123', 10);
  const createdAnggota: Array<{ id: number; email: string }> = [];

  for (const data of anggotaData) {
    const anggota = await prisma.anggota.upsert({
      where: { nomorAnggota: data.nomorAnggota },
      update: {},
      create: {
        nomorAnggota: data.nomorAnggota,
        namaLengkap: data.namaLengkap,
        jenisKelamin: data.jenisKelamin,
        tempatLahir: data.tempatLahir,
        tanggalLahir: data.tanggalLahir,
        alamat: data.alamat,
        noHp: data.noHp,
        email: data.email,
        rantingId: ranting.id,
        statusKeanggotaan: 'aktif',
        statusData: 'complete',
        statusValidasi: 'approved',
      },
    });

    createdAnggota.push({ id: anggota.id, email: data.email! });

    // Create user account linked to anggota
    const nameSlug = data.namaLengkap.toLowerCase().replace(/\s+/g, '.');
    await prisma.user.upsert({
      where: { email: data.email },
      update: {},
      create: {
        name: data.namaLengkap,
        email: data.email,
        nomorHp: data.noHpUser,
        passwordHash: anggotaPassword,
        roleId: 7,
        anggotaId: anggota.id,
        isActive: true,
      },
    });
  }
  console.log(`✓ Created ${anggotaData.length} anggota with user accounts`);

  // ═══════════════════════════════════════════
  // CALON ANGGOTA
  // ═══════════════════════════════════════════
  const calonData = [
    { namaLengkap: 'Gabriel F. Mau', jenisKelamin: 'L', noHp: '081234567811' },
    { namaLengkap: 'Veronika K. Bura', jenisKelamin: 'P', noHp: '081234567812' },
  ];

  for (const c of calonData) {
    await prisma.calonAnggota.create({
      data: {
        namaLengkap: c.namaLengkap,
        jenisKelamin: c.jenisKelamin,
        noHp: c.noHp,
        rantingId: ranting.id,
        usulOlehUserId: admin.id,
        status: 'diusulkan',
      },
    });
  }
  console.log(`✓ Created ${calonData.length} calon anggota`);

  // ═══════════════════════════════════════════
  // ASPEK PENILAIAN + ITEM PENILAIAN
  // ═══════════════════════════════════════════
  const aspekData = [
    { kodeAspek: 'KITAB_SUCI', namaAspek: 'Pengetahuan Kitab Suci', bobot: 25, deskripsi: 'Pengetahuan tentang Kitab Suci Perjanjian Lama dan Baru' },
    { kodeAspek: 'DOKTRIN', namaAspek: 'Doktrin Gereja Katolik', bobot: 25, deskripsi: 'Pemahaman tentang ajaran dasar Gereja Katolik' },
    { kodeAspek: 'SEJARAH', namaAspek: 'Sejarah THS-THM', bobot: 20, deskripsi: 'Pengetahuan tentang sejarah berdirinya THS-THM' },
    { kodeAspek: 'PRAKTIK', namaAspek: 'Praktik Kepemimpinan', bobot: 15, deskripsi: 'Kemampuan memimpin dan mengorganisir kegiatan' },
    { kodeAspek: 'LAGU_LITURGI', namaAspek: 'Lagu & Liturgi', bobot: 15, deskripsi: 'Pengetahuan lagu gerejani dan tata liturgi' },
  ];

  const itemData: Array<{ kodeItem: string; namaItem: string; aspekKode: string; skorMaksimal: number; bobot: number; urutan: number }> = [
    { kodeItem: 'PL_DASAR', namaItem: 'Perjanjian Lama - Dasar', aspekKode: 'KITAB_SUCI', skorMaksimal: 100, bobot: 40, urutan: 1 },
    { kodeItem: 'PB_DASAR', namaItem: 'Perjanjian Baru - Dasar', aspekKode: 'KITAB_SUCI', skorMaksimal: 100, bobot: 40, urutan: 2 },
    { kodeItem: 'INJIL_SINOPTIK', namaItem: 'Injil Sinoptik', aspekKode: 'KITAB_SUCI', skorMaksimal: 100, bobot: 20, urutan: 3 },
    { kodeItem: 'KREDO', namaItem: 'Credo / Syahadat', aspekKode: 'DOKTRIN', skorMaksimal: 100, bobot: 50, urutan: 1 },
    { kodeItem: 'SAKRAMEN', namaItem: 'Sakramen', aspekKode: 'DOKTRIN', skorMaksimal: 100, bobot: 50, urutan: 2 },
    { kodeItem: 'BERDIRI', namaItem: 'Sejarah Berdiri THS', aspekKode: 'SEJARAH', skorMaksimal: 100, bobot: 50, urutan: 1 },
    { kodeItem: 'TOKOH', namaItem: 'Tokoh Pendiri', aspekKode: 'SEJARAH', skorMaksimal: 100, bobot: 50, urutan: 2 },
    { kodeItem: 'ORGANISASI', namaItem: 'Organisasi & AD/ART', aspekKode: 'PRAKTIK', skorMaksimal: 100, bobot: 40, urutan: 1 },
    { kodeItem: 'PUBLIC_SPEAKING', namaItem: 'Public Speaking', aspekKode: 'PRAKTIK', skorMaksimal: 100, bobot: 60, urutan: 2 },
    { kodeItem: 'LAGU_GEREJA', namaItem: 'Lagu Gerejani', aspekKode: 'LAGU_LITURGI', skorMaksimal: 100, bobot: 60, urutan: 1 },
    { kodeItem: 'TATA_LITURGI', namaItem: 'Tata Liturgi', aspekKode: 'LAGU_LITURGI', skorMaksimal: 100, bobot: 40, urutan: 2 },
  ];

  // Create aspects first
  for (const a of aspekData) {
    const aspek = await prisma.aspekPenilaian.upsert({
      where: { kodeAspek: a.kodeAspek },
      update: {},
      create: a,
    });

    // Create items for this aspect
    const itemsForAspek = itemData.filter((i) => i.aspekKode === a.kodeAspek);
    for (const item of itemsForAspek) {
      await prisma.itemPenilaian.upsert({
        where: { kodeItem: item.kodeItem },
        update: {},
        create: {
          kodeItem: item.kodeItem,
          namaItem: item.namaItem,
          aspekId: aspek.id,
          skorMaksimal: item.skorMaksimal,
          bobot: item.bobot,
          urutan: item.urutan,
        },
      });
    }
  }
  console.log(`✓ Created ${aspekData.length} aspek penilaian with ${itemData.length} items`);

  // ═══════════════════════════════════════════
  // JENIS IURAN
  // ═══════════════════════════════════════════
  const jenisIuranList = [
    { nama: 'Iuran Wajib Bulanan', nominal: 50000, periode: 'bulanan', scopeType: 'distrik', scopeId: distrik.id },
    { nama: 'Iuran Tahunan', nominal: 500000, periode: 'tahunan', scopeType: 'nasional', scopeId: nasional.id },
  ];

  for (const ji of jenisIuranList) {
    await prisma.jenisIuran.create({ data: ji });
  }
  console.log(`✓ Created ${jenisIuranList.length} jenis iuran`);

  // ═══════════════════════════════════════════
  // PEMBAYARAN IURAN (sample)
  // ═══════════════════════════════════════════
  const jenisIuranBulanan = await prisma.jenisIuran.findFirst({ where: { periode: 'bulanan' } });
  if (jenisIuranBulanan) {
    for (const anggota of createdAnggota) {
      for (let month = 1; month <= 6; month++) {
        await prisma.pembayaranIuran.create({
          data: {
            jenisIuranId: jenisIuranBulanan.id,
            anggotaId: anggota.id,
            jumlahBayar: 50000,
            tanggalBayar: new Date(2024, month, 15),
            metodeBayar: 'tunai',
            status: 'lunas',
          },
        });
      }
    }
    console.log(`✓ Created sample iuran payments for ${createdAnggota.length} anggota`);
  }

  // ═══════════════════════════════════════════
  // KONTEN (sample)
  // ═══════════════════════════════════════════
  const kontenData = [
    { judul: 'Perayaan Paskah THS-THM 2024', jenis: 'Berita', konten: 'Perayaan Paskah tahun ini diadakan di Gereja Katedral Larantuka dengan dihadiri oleh seluruh anggota THS-THM dari berbagai ranting.', status: 'Dipublikasikan' },
    { judul: 'Materi Latihan: Kepemimpinan Kristiani', jenis: 'Artikel', konten: 'Kepemimpinan Kristiani adalah pelayanan yang didasarkan pada nilai-nilai Injil...', status: 'Dipublikasikan' },
    { judul: 'Ret Anggota Baru 2024', jenis: 'Acara', konten: 'Ret-ret anggota baru akan diadakan pada tanggal 20-22 Desember 2024 di Pusat Ret-ret Larantuka.', status: 'Menunggu Persetujuan' },
    { judul: 'Renungan Mingguan: Kasih Persaudaraan', jenis: 'Artikel', konten: 'Kasih persaudaraan merupakan ciri khas pengikut Kristus...', status: 'Dipublikasikan' },
  ];

  for (const k of kontenData) {
    await prisma.konten.create({
      data: {
        judul: k.judul,
        jenis: k.jenis,
        konten: k.konten,
        status: k.status,
        penulisId: admin.id,
        publishedAt: k.status === 'Dipublikasikan' ? new Date() : null,
      },
    });
  }
  console.log('✓ Created sample konten');

  // ═══════════════════════════════════════════
  // SYNC SEQUENCES (PostgreSQL)
  // ═══════════════════════════════════════════
  const sequences = [
    'roles_id_seq', 'nasional_id_seq', 'distrik_id_seq', 'wilayah_id_seq', 'ranting_id_seq',
    'users_id_seq', 'anggota_id_seq', 'calon_anggota_id_seq',
    'document_types_id_seq', 'aspek_penilaian_id_seq', 'item_penilaian_id_seq',
    'jenis_iuran_id_seq', 'konten_id_seq',
  ];

  for (const seq of sequences) {
    try {
      await prisma.$executeRawUnsafe(`SELECT setval('"${seq}"', (SELECT MAX(id) FROM "${seq.replace('_id_seq', '')}"));`);
    } catch {
      // Some tables might be empty or view, skip errors
    }
  }

  console.log('\n✅ Seeding completed!');
  console.log('\n📋 Login credentials:');
  console.log('   Admin:   admin@ths-thm.org / admin123');
  console.log('   Pelatih: pelatih@ths-thm.org / pelatih123');
  console.log('   Anggota: yohanes@example.com / anggota123');
}

main()
  .catch((e) => {
    console.error('❌ Seed error:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
